---
- name: shutdown spring-boot-sample.service
  systemd:
    name: spring-boot-sample.service
    state: stopped

- name: deploy spring-boot-sample file from jenkins to remote
  get_url:
    url: http://172.16.165.10/job/spring-boot-sample-pipeline/lastStableBuild/artifact/build/libs/spring-boot-sample-0.0.1.jar
    dest: /home/sbadmin/spring-boot-sample-0.0.1.jar
    owner: sbadmin
    group: sbadmin
    mode: 0755
    url_username: jkadmin
    url_password: 5a54cf80bf7f0549cf57c92a4ac9538b
    force_basic_auth: yes

- name: deploy spring-boot-sample.service file
  copy:
    src: spring-boot-sample.service
    dest: /etc/systemd/system/spring-boot-sample.service
    owner: root
    group: root
    mode: 0664

- name: reload spring-boot-sample.service
  systemd:
    daemon_reload: yes
    name: spring-boot-sample.service
    enabled: yes
    state: started
