---
- name: create app group {{ app_user }}
  group: 
    name: "{{ app_user }}"
    system: yes
    state: present

- name: create app user {{ app_user }}
  user:
    name: "{{ app_user }}"
    system: yes
    state: present
    home: "/opt/{{ app_user }}"
    shell: /bin/bash

- name: shutdown {{ app_name }} service
  systemd:
    name: "{{ app_name }}.service"
    state: stopped

- name: deploy {{ app_name }} file
  get_url:
    url: "{{ app_download_url }}"
    dest: "/opt/{{ app_user }}/{{ app_name }}-{{ app_version }}.jar"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0755
    url_username: "{{ app_download_url_user }}"
    url_password: "{{ app_download_url_password }}"
    force_basic_auth: yes

- name: deploy {{ app_name }} service file
  template:
    src: "{{ app_name }}.j2"
    dest: "/etc/systemd/system/{{ app_name }}.service"
    owner: root
    group: root
    mode: 0664

- name: reload {{ app_name }} service
  systemd:
    daemon_reload: yes
    name: "{{ app_name }}.service"
    enabled: yes
    state: started
